### ISSUE TITLE
tools has expired

### ISSUE THREAD

**Issue by dapple2** [xAranaktu/FIFASquadFileDownloader#4]
Currently unable to download the squads, prompting an error

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)>

**Comment by xAranaktu** [comment]
Works fine for me.

**Comment by dapple2** [comment]
from yesterday to today,I have tested many times on different computers and different networks, and they all prompt this error，This tool was working fine before.You can see the picture, there are detailed errors in it.

https://s1.locimg.com/2023/03/13/16531e5e3ace0.JPG

**Comment by dapple2** [comment]
D:\个人\F\FIFA23\tools\FIFASquadFileDownloader-main2\FIFASquadFileDownloader-main>main.py
Download: https://fifa23.content.easports.com/fifa/fltOnlineAssets/23DF3AC5-9539-438B-8414-146FAFDE3FF2/2023/fifa/fifalive/genxtitle/rosterupdate.xml
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 950, in send
    self.connect()
  File "D:\Program Files (x86)\Python38-32\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\Program Files (x86)\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Program Files (x86)\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Program Files (x86)\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\个人\F\FIFA23\tools\FIFASquadFileDownloader-main2\FIFASquadFileDownloader-main\main.py", line 418, in <module>
    result = process_rosterupdate()
  File "D:\个人\F\FIFA23\tools\FIFASquadFileDownloader-main2\FIFASquadFileDownloader-main\main.py", line 92, in process_rosterupdate
    download_rosterupdate()
  File "D:\个人\F\FIFA23\tools\FIFASquadFileDownloader-main2\FIFASquadFileDownloader-main\main.py", line 27, in download_rosterupdate
    download(ROSTERUPDATE_XML, roster_update_url)
  File "D:\个人\F\FIFA23\tools\FIFASquadFileDownloader-main2\FIFASquadFileDownloader-main\main.py", line 21, in download
    response = urllib.request.urlopen(url)
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Program Files (x86)\Python38-32\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)>

**Comment by xAranaktu** [comment]
As I said, I've tested the script 5 min ago and it is working fine for me. It's something on your end. I don't know what, never seen this error before. Uncle Google should be able to help you with it.

**Comment by dapple2** [comment]
Ok,Thanks,i have solved it,I have a question, is there a way to support nintendo switch FIFA23 squads download

**Comment by xAranaktu** [comment]
I don't think so. The place where PC squad files are stored doesn't have squad files for nintendo switch.
